### ISSUE TITLE
Error to get item schema, steam api update

### ISSUE THREAD

**Issue by DemonAk** [Jessecar96/SteamBot#1126]
i think this error issue because steam update api and need to be fixed
new urls
https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1/?key=
https://api.steampowered.com/IEconItems_440/GetSchemaOverview/v1/?key=

**Comment by nightfuryninja** [comment]
I just tested this. The second link seems to load faster, however, both return the schema. I will keep an eye on this issue just in case I have experienced this before.

**Comment by DemonAk** [comment]
yep, second link faster load but not full item schema.
First link it's a full item schema divided into several pages, "next": 1150
1 https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1/?key=
2 https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1/?key=&start=1150
3 https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1/?key=&start=8303
4 https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1/?key=&start=9336
5 https://api.steampowered.com/IEconItems_440/GetSchemaItems/v1/?key=&start=30112

**Comment by kilpkonn** [comment]
I made quick fix for it, works fine for me. May need rewrite though.

https://github.com/kilpkonn/SteamBot/commit/3168473a5360a87808b13118f9d23ef660fe1116

**Comment by DemonAk** [comment]
It works, but where scheme is downloaded?. I can't find file шт C:\Users\User\AppData\Local\Temp
only directroy with file C:\Users\User\AppData\Local\Temp\MetadataAsSource\Path.cs

**Comment by nightfuryninja** [comment]
The schema should be cached into the bin folder. The file's name is "tf_schema.cache". Inside is where it contains all the information. 

There is a massive difference. between the two APIs. Just compare the two and you will see the old schema (works fine as you already know, this is slower but only needs to be fetched when it is updated) has more information about items.

The change that needs making is if the API gives off anything other than the code 200 we load all of the data from the cached schema. This will fix all issues with the bot and will allow it to keep operating even when it goes down. The other option is, of course, to remove schema completely and rely upon one of the other steam APIs (let me check) to fetch the data.

Changing the schema won't fix the issue because when the TF2 API goes down, both of them will become unavailable.

**Comment by nightfuryninja** [comment]
I am just going to leave this question here for you to reply to. What information do you actually require for your bot to function? If you are not trading within TF2 or do not require TF2 information about the item you can ignore the schema completely. 

One method of getting the information you might need is using the API seen here "https://partner.steamgames.com/doc/webapi/IInventoryService#GetInventory"

**Comment by nightfuryninja** [comment]
@DemonAk Could you close this issue as the pull request has been merged? 

Thanks
