### ISSUE TITLE
Offer send not working

### ISSUE THREAD

**Issue by glukamin** [Jessecar96/SteamBot#810]
Hi,

I am trying to use existing code for trades, and when ever I call:
string newOfferId;
offer.Send(out newOfferId)
I get:
The remote server returned an error: (500) Internal Server Error
This is the url in the Request method of SteamWeb.cs:
https://steamcommunity.com/tradeoffer/new/send
but even when I type this in browser I get null.
I am doing something wrong or what? Btw the referer parameter in this method is ok, I tried it in browser and works fine.

Thanks,

**Comment by TheAnthonyNL** [comment]
This is due the fact that steam is down. Just retry or create while loop onto it...

**Comment by glukamin** [comment]
It is persistent in failing. 
>request.GetResponse() as HttpWebResponse 
So I can read request but can you help where can I look further since I am not that much familiar with web. I also get this error: The remote server returned an error: (401) Unauthorized. I can paste Header with its errors if that will help.

**Comment by scholtzm** [comment]
@TheAnthonyNL That would be a terrible approach. There's many reasons why the trade offer won't be sent and it's not because of Steam servers being down. You can easily generate HTTP non-200 code by adding an item with incorrect assetid.

In reality, `SteamWeb` should [read the response even if an exception is thrown](http://stackoverflow.com/questions/692342/net-httpwebrequest-getresponse-raises-exception-when-http-status-code-400-ba/692369#692369).

The response will in many cases contain message similar to this: `Error: There was an error sending your trade offer. Please try again later. (x)` where `x` is a number corresponding to `EResult` enum.

**Comment by glukamin** [comment]
{"strError":"There was an error sending your trade offer. Please >try again later. (26)"}

This is what I got as an error.

**Comment by glukamin** [comment]
Sry, it was wrong ID, now when I put the right one in browser it work but not from code.

**Comment by glukamin** [comment]
I was sending a wrong AssetID... OMG!!! Thanks everyone for helping...

**Comment by behzadrb495** [comment]
hi , Please Help me I have this problem
I changed AssetID but failed
 , Please send for me your project 
Email : H.RassafBakhsh@gmail.com
Thanx
